version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: imagesdb
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgresql_container

volumes:
  db_data:
